version: '2'
services:
  app:
    build:
      context: ./apache/php5.6
      dockerfile: Dockerfile
    image: dev:apache_php5.6
    container_name: app
    ports:
      - "80:80"
    environment:
      APP_ENV: dev
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=192.168.2.11
    volumes:
      - ~/Codebase:/var/www
      - ~/Codebase/server/apache/conf/sites-available:/etc/apache2/sites-available
    networks:
      - devnet
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      - "3306:3306"
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - devnet
networks:
  devnet:
    driver: bridge
volumes:
  mysqldb:
    driver: local
